# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded mycons 1.0 [list source [file join $dir mycons.tcl]]
package ifneeded mydoc 1.0 [list source [file join $dir mydoc.tcl]]
package ifneeded mydsp 1.0 [list source [file join $dir mydsp.tcl]]
package ifneeded mylsn 1.0 [list source [file join $dir mylsn.tcl]]
package ifneeded mym 1.0 [list load [file join $dir mym.dll]]
package ifneeded mysens 1.0 [list source [file join $dir mysens.tcl]]
package ifneeded myser 1.0 [list source [file join $dir myser.tcl]]
package ifneeded myutl 1.0 [list source [file join $dir myutl.tcl]]
package ifneeded ui_3d 1.0 [list source [file join $dir ui_3d.tcl]]
package ifneeded ui_cells 1.0 [list source [file join $dir ui_cells.tcl]]
package ifneeded ui_eeprom 1.0 [list source [file join $dir ui_eeprom.tcl]]
package ifneeded ui_main 1.0 [list source [file join $dir ui_main.tcl]]
package ifneeded ui_plot 1.0 [list source [file join $dir ui_plot.tcl]]
